# This task configures the required DNS records for the given domains.
---
- name: Check Cloudflare credentials
  assert:
    that:
      - module.config.cloudflare_api_token|d("") != ""
- name: "Create A record for domain {{ item.domain }}"
  include_tasks: "{{ module_role_path | default(role_path) }}/tasks/steps/records/a.yml"
  vars:
    domain: "{{ item.domain }}"
    state: present
  when: item.dns.provider|d('') == 'getstackhead.stackhead_dns_cloudflare'
  with_items: "{{ app_config.domains }}" # item.domain
