# This task configures the required DNS records for the given domains.
---
- name: Check Cloudflare credentials
  assert:
    that:
      - module.config.cloudflare_email|d("") != ""
      - module.config.cloudflare_api_token|d("") != ""
- name: "Create A record for domain {{ item.domain }}"
  cloudflare_dns:
    zone: "{{ item.domain|getstackhead.stackhead.domain }}"
    record: "{{ item.domain|getstackhead.stackhead.subdomain|d('@', true) }}"
    type: A
    value: "{{ ansible_ssh_host }}"
    account_email: "{{ module.config.cloudflare_email }}"
    account_api_token: "{{ module.config.cloudflare_api_token }}"
    proxied: no
    solo: yes
    state: present
  when: item.dns.provider|d('') == 'cloudflare'
  with_items: "{{ app_config.domains }}" # item.domain
