# This task removes the DNS configurations for the given domains.
---
- name: Check Cloudflare credentials
  assert:
    that:
      - module.config.cloudflare_api_token|d("") != ""
- name: "Remove A record for domain {{ item.domain }}"
  cloudflare_dns:
    zone: "{{ item.domain|getstackhead.stackhead.domain }}"
    record: "{{ item.domain|getstackhead.stackhead.subdomain|d('@', true) }}"
    type: A
    value: "{{ ansible_ssh_host }}"
    api_token: "{{ module.config.cloudflare_api_token }}"
    state: absent
  when: item.dns.provider|d('') == 'cloudflare'
  with_items: "{{ app_config.domains }}" # item.domain
